### ISSUE TITLE
Problem with build_map.py

### ISSUE THREAD

**Issue by hermanekt** [infery/zabbix-map-creator#6]
Hi,

can you help me with building map please? I try all steps and when i try to build map i have problem. If i disable zabbix in conf, script create file. When i have enable zabbix i have this exeption.

I use zabbix 4.2, centos 7

```console
[root@hermanek-lab zabbix-map-creator]# ./arp.py test.ini
added c0:25:5c:ff:70:48 ip 192.168.248.7
added c0:25:5c:ff:65:c7 ip 192.168.248.10
added 1c:e8:5d:ff:36:46 ip 192.168.248.15
added 18:8b:45:2b:21:c7 ip 192.168.248.17
added 00:45:1d:96:2f:43 ip 192.168.248.254

!UPLINK MAC-ADDRESS MUST BE IN ARP TABLE!
```
```console
[root@hermanek-lab zabbix-map-creator]# ./get_mac_form_switches.py test.ini
Connect to 192.168.248.15 , vendor cisco
Collected mac from 1 ports
After cleaning left 1 ports
192.168.248.15 added mac 00:45:1d:96:2f:43 on port Gi1/0/48
====================
Connect to 192.168.248.17 , vendor cisco
Collected mac from 1 ports
After cleaning left 1 ports
192.168.248.17 added mac 00:45:1d:96:2f:43 on port Gi1/0/48
====================
Connect to 192.168.248.10 , vendor cisco
Collected mac from 3 ports
After cleaning left 1 ports
192.168.248.10 added mac 00:45:1d:96:2f:43 on port Gi1/0/48
====================
Connect to 192.168.248.254 , vendor cisco
Collected mac from 22 ports
After cleaning left 1 ports
192.168.248.254 added mac c0:25:5c:ff:65:c7 on port Po2
192.168.248.254 added mac 18:8b:45:2b:21:c7 on port Po2
192.168.248.254 added mac c0:25:5c:ff:70:48 on port Po2
192.168.248.254 added mac 1c:e8:5d:ff:36:46 on port Po2
====================
Connect to 192.168.248.7 , vendor cisco
Collected mac from 5 ports
After cleaning left 4 ports
192.168.248.7 added mac c0:25:5c:ff:65:c7 on port Gi1/0/48
192.168.248.7 added mac 00:45:1d:96:2f:43 on port Po1
192.168.248.7 added mac 1c:e8:5d:ff:36:46 on port Gi1/0/47
192.168.248.7 added mac 18:8b:45:2b:21:c7 on port Gi1/0/46
====================
```
```console
[root@hermanek-lab zabbix-map-creator]# ./build_map.py test.ini
Using configured uplink mac 00:45:1d:96:2f:43

[|] Update info about uplinks in db
[|] Check edge status of device
Traceback (most recent call last):
  File "./build_map.py", line 331, in <module>
    'selementid1': devices[eselement1]['id_on_map'],
KeyError: u'92.168.248.254'
[root@hermanek-lab zabbix-map-creator]#
```
## Config:
```console
[root@hermanek-lab zabbix-map-creator]# cat test.ini

[network]
; switch's default gateway mac address
uplink_mac = 0045.1d96.2f43
; switches creditionals
sw_username = cisco
sw_password = cisco
; sqlite database filename
database = test.db
; from wich file to load 'show ip arp'
arp_file_type = cisco
file_with_arp = test-cisco-show-ip-arp.txt

[zabbix]
; use zabbix.
; yes, true - build map in zabbix
; no, false - dont touch zabbix, generate only dot file with <mapname>
use_zabbix = yes
; zabbix api creditionals
username = zabbix
password = zabbix
; zabbix server url
zbx_url = http://zabbixserver/
; zabbix map to be created
mapname = TEST-NETWORK
```

## Show ip arp
```console
[root@hermanek-lab zabbix-map-creator]# cat test-cisco-show-ip-arp.txt
Internet  192.168.248.7          10   c025.5cff.7048  ARPA   Vlan248
Internet  192.168.248.10          4   c025.5cff.65c7  ARPA   Vlan248
Internet  192.168.248.15          4   1ce8.5dff.3646  ARPA   Vlan248
Internet  192.168.248.17         15   188b.452b.21c7  ARPA   Vlan248
Internet  192.168.248.254         -   0045.1d96.2f43  ARPA   Vlan248
```

**Comment by hermanekt** [comment]
Hi,
think i'm found first problem is with regular expresion at the line 331. I'm using 3 strings, you using only 2 (**192**.168.248.254 vs 10.10.1.1):
        for m in re.findall(r'(?=([1-9][0-9]+\.\d+\.\d+\.\d+)==([1-9][0-9]+\.\d+\.\d+\.\d+))', lnk_str):
change in to this:
        for m in re.findall(r'(?=([1-9]**[0-9]**[0-9]+\.\d+\.\d+\.\d+)==([1-9]**[0-9]**[0-9]+\.\d+\.\d+\.\d+))', lnk_str):

After this change i have error from API (I'm using super admin account):

```console
[root@hermanek-lab zabbix-map-creator]# ./build_map.py test.ini
Using configured uplink mac 00:45:1d:96:2f:43

[|] Update info about uplinks in db
[|] Check edge status of device
Traceback (most recent call last):
  File "./build_map.py", line 352, in <module>
    mheight=max_height)
  File "/root/zabbix-map-creator/zabbix.py", line 46, in create_or_update_map
    'links': links
  File "/usr/lib/python2.7/site-packages/pyzabbix/api.py", line 263, in do_request
    raise ZabbixAPIException(err)
pyzabbix.api.ZabbixAPIException: {u'message': u'Application error.', u'code': -32500, u'data': u'No permissions to referred object or it does not exist!', 'json': "{'params': {'width': 500, 'selements': [{'elements': [{'hostid': 10273}], 'y': 60, 'iconid_off': '2', 'selementid': 1, 'x': 100, 'elementtype': 0}, {'elements': [{'hostid': 10283}], 'y': 300, 'iconid_off': '2', 'selementid': 2, 'x': 100, 'elementtype': 0}, {'elements': [{'hostid': 10282}], 'y': 540, 'iconid_off': '2', 'selementid': 3, 'x': 100, 'elementtype': 0}, {'elements': [{'hostid': 10281}], 'y': 360, 'iconid_off': '2', 'selementid': 4, 'x': 200, 'elementtype': 0}, {'elements': [{'hostid': 10284}], 'y': 300, 'iconid_off': '2', 'selementid': 5, 'x': 300, 'elementtype': 0}], 'name': u'TEST-NETWORK', 'links': [{'color': '00FF00', 'selementid1': 1, 'selementid2': 2}, {'color': '00FF00', 'selementid1': 2, 'selementid2': 3}, {'color': '00FF00', 'selementid1': 2, 'selementid2': 4}, {'color': '00FF00', 'selementid1': 2, 'selementid2': 5}], 'height': 880}, 'jsonrpc': '2.0', 'method': 'map.create', 'auth': u'377c37ef152dfef27e0390a7f9a70ed6', 'id': '1'}"}
```

**Comment by hermanekt** [comment]
Hi,

sorry i don't have host in zabbix, my colegue deleted him. After again add all is ok. But i stlill need changed regular.

Tom

**Comment by hermanekt** [comment]
Hi Artem,

i tested your fix and it works! Thank you, for fast reply and fix. You can close this issue:)

Tom
